### ISSUE TITLE
Where is the test.py

### ISSUE THREAD

**Issue by gachiemchiep** [PingoLH/FCHarDNet#1]
Hello buddy.
Thank you for your implementation.

Unfortunately, i can't find the test.py anywhere.
Do you have any plan to implement it.

**Comment by PingoLH** [comment]
Hello, 
Thank you for asking. If you are interested in testing with testset, you can modify the config file with "val_split: test" then run validate.py + --save_image. It will write prediction results into out_rgb/
If you are interested in testing with custom images, please refer to the test.py in https://github.com/meetshah1995/pytorch-semseg. It should be compatible since FCHarDNet repo was forked from here.

**Comment by gachiemchiep** [comment]
Hello @PingoLH 
There's some change that need to be made, but it can test and write the image now. 
Just one more question but do you know how to change the input shape?
Will change the shape of data_loader is enough to accomplish that ? 

```bash
    loader = data_loader(
        data_path,
        split=cfg["data"]["val_split"],
        is_transform=True,
        img_size=(1024,2048),    <---- this line ???
    ) 
```
